### ISSUE TITLE
Add `name` parameter to `Option` and `Flag`

### ISSUE THREAD

**Issue by seaneagan** [seaneagan/unscripted#91]
useful when the dart identifier doesn't map cleanly to the desire option-name e.g. when you want to use a dart reserved word as an option name.

**Comment by BlackHC** [comment]
I just wanted to file a similar request. Especially when you set multiple: true, you probably want your parameter name to be plural while the option would be singular:
```
...
@Option(name='target', multiple: true)
List<String> targets,
...
```
What do you think?
Thanks,
 Andreas
